/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pcd.gui.dialog;

import java.awt.Point;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.SwingWorker;
import pcd.data.PcdPoint;
import pcd.gui.MainFrame;
import pcd.python.PythonProcess;

/**
 *
 * @author ixenr
 */
public class AngleLoadingDialog extends JDialog {
    
    MainFrame parentFrame;
    private final PythonProcess pyproc;
    private final String imgPath;
    private final ArrayList<Point> pointList;
    private final JDialog thisDialog = this;
    private ArrayList<Double> result = new ArrayList<>();
    private ImgTask imgtask;

    public AngleLoadingDialog(MainFrame parentFrame, PythonProcess pyproc, String imgPath, ArrayList<Point> pointList) {
        super(parentFrame, true);
        initComponents();
        this.parentFrame = parentFrame;
        this.pyproc = pyproc;
        this.imgPath = imgPath;
        this.pointList = pointList;
    }
    
    public ArrayList<Double> showDialog(){
        (imgtask = new ImgTask()).execute();
        setVisible(true);
        return result;  
    }
    
    private class ImgTask extends SwingWorker<Void, String> {

        @Override
        protected Void doInBackground() throws Exception {
            try{
                result = pyproc.getAngles(imgPath, pointList);
            }catch(IOException e){}
            
            thisDialog.setVisible(false);
            thisDialog.dispose();
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Loading");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Loading, please wait.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
